### ISSUE TITLE
The access_token method does not check if the API call succeeded

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/manifester#42]
```
$ manifester inventory --sync
Traceback (most recent call last):
  File "/home/ogajduse/.virtualenvs/robottelo/bin/manifester", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/manifester/commands.py", line 80, in inventory
    helpers.update_inventory(Manifester(minimal_init=True).subscription_allocations)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/manifester/manifester.py", line 144, in subscription_allocations
    return fetch_paginated_data(self, "allocations")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/manifester/helpers.py", line 88, in fetch_paginated_data
    "headers": {"Authorization": f"Bearer {manifester.access_token}"},
                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ogajduse/.virtualenvs/robottelo/lib/python3.12/site-packages/manifester/manifester.py", line 118, in access_token
    self._access_token = token_data["access_token"]
                         ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'
```

Debugging it a bit:
```
(Pdb++) res = simple_retry(self.requester.post, cmd_args=[f"{self.token_request_url}"], cmd_kwargs=token_request_data)
(Pdb++) res
<Response [400]>                                                                                                                                                                                  
(Pdb++) res.ok
False
(Pdb++) res.json()
{'error': 'invalid_grant', 'error_description': 'Invalid refresh token'}
```

**Comment by synkd** [comment]
@ogajduse I believe https://github.com/SatelliteQE/manifester/pull/45 addresses this issue, could you please confirm?

**Comment by ogajduse** [comment]
It seems it does
